[package]
name = "house-price-predictor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
polars = { version = "0.44.2", features = ["csv", "lazy", "strings"] }
rand = "0.8.5"
reqwest = { version = "0.12.9", features = ["blocking"] }
